/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author gilli
 */
public class frameMenu extends javax.swing.JFrame {

    /**
     * Creates new form frameMenu
     */
    public frameMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuFrame = new javax.swing.JMenu();
        menuMorador = new javax.swing.JMenuItem();
        menuApartamento = new javax.swing.JMenuItem();
        menuGaragem = new javax.swing.JMenuItem();
        menuConta = new javax.swing.JMenuItem();
        menuSalaofesta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuFrame.setText("Arquivos");

        menuMorador.setText("Morador");
        menuMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMoradorActionPerformed(evt);
            }
        });
        menuFrame.add(menuMorador);

        menuApartamento.setText("Apartamento");
        menuApartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuApartamentoActionPerformed(evt);
            }
        });
        menuFrame.add(menuApartamento);

        menuGaragem.setText("Garagem");
        menuGaragem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGaragemActionPerformed(evt);
            }
        });
        menuFrame.add(menuGaragem);

        menuConta.setText("Conta");
        menuConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuContaActionPerformed(evt);
            }
        });
        menuFrame.add(menuConta);

        menuSalaofesta.setText("Reserva Salão de Festa");
        menuSalaofesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalaofestaActionPerformed(evt);
            }
        });
        menuFrame.add(menuSalaofesta);

        jMenuBar1.add(menuFrame);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMoradorActionPerformed
        // TODO add your handling code here:
         new dialogMorador(this, true).setVisible(true);
    }//GEN-LAST:event_menuMoradorActionPerformed

    private void menuApartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuApartamentoActionPerformed
        // TODO add your handling code here:
        new dialogApartamento(this, true).setVisible(true);
    }//GEN-LAST:event_menuApartamentoActionPerformed

    private void menuSalaofestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalaofestaActionPerformed
        // TODO add your handling code here:
        new dialogSalaofesta(this, true).setVisible(true);
    }//GEN-LAST:event_menuSalaofestaActionPerformed

    private void menuContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuContaActionPerformed
        // TODO add your handling code here:
        new dialogConta(this, true).setVisible(true);
    }//GEN-LAST:event_menuContaActionPerformed

    private void menuGaragemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGaragemActionPerformed
        // TODO add your handling code here:
        new dialogGaragem(this, true).setVisible(true);
    }//GEN-LAST:event_menuGaragemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuApartamento;
    private javax.swing.JMenuItem menuConta;
    private javax.swing.JMenu menuFrame;
    private javax.swing.JMenuItem menuGaragem;
    private javax.swing.JMenuItem menuMorador;
    private javax.swing.JMenuItem menuSalaofesta;
    // End of variables declaration//GEN-END:variables
}
